version: '3.8'

services:
  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: booking_platform
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - booking_platform_network

  frontend_service:
    image: nginx:latest
    ports:
      - "8000:8000"
    networks:
      - booking_platform_network

  users_service:
    build:
      context: ./services/users/app
    ports:
      - "8001:8001"
    depends_on:
      - postgres_db
    networks:
      - booking_platform_network

  venues_service:
    build:
      context: ./services/venues/app
    ports:
      - "8002:8002"
    depends_on:
      - postgres_db
    networks:
      - booking_platform_network

  reservations_service:
    build:
      context: ./services/reservations/app
    ports:
      - "8003:8003"
    depends_on:
      - postgres_db
    networks:
      - booking_platform_network

  notifications_service:
    build:
      context: ./services/notifications
    ports:
      - "8004:8004"
    networks:
      - booking_platform_network

networks:
  booking_platform_network:
    driver: bridge

volumes:
  postgres_data:
